### ISSUE TITLE
fails when both GPU and CPU platforms exist

### ISSUE THREAD

**Issue by claudeha** [jdanecki/FractalCL#1]
I have `amd-opencl-icd` installed from `jessie-backports` `non-free` section on my Debian Buster system so I can test OpenCL on my CPU (less risk of crashing with exceeded timeouts, etc).  I also have the Mesa OpenCL driver for my GPU.  The program aborts on startup, presumably because it wants a GPU from the second platform (which is CPU).  There should ideally be a dialog to select the platform and device, and not absolutely require GPU because OpenCL can run fine on CPU too, though perhaps less fast.  Here's the output from the program:

    found 2 platforms
    --- platform: Clover
    GPU device: Radeon RX 580 Series (POLARIS10 / DRM 3.23.0 / 4.16.0-2-amd64, LLVM 6.0.0)
    MAX_COMPUTE_UNITS=36
    MAX_WORKGROUP_SIZE=256
    --- platform: AMD Accelerated Parallel Processing
    OCL GPU device not found err=-1

And here are the first few lines from `clinfo`:

    Number of platforms                               2
      Platform Name                                   Clover
      Platform Vendor                                 Mesa
      Platform Version                                OpenCL 1.1 Mesa 18.0.5
      Platform Profile                                FULL_PROFILE
      Platform Extensions                             cl_khr_icd
      Platform Extensions function suffix             MESA
    
      Platform Name                                   AMD Accelerated Parallel Processing
      Platform Vendor                                 Advanced Micro Devices, Inc.
      Platform Version                                OpenCL 2.0 AMD-APP (1912.5)
      Platform Profile                                FULL_PROFILE
      Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
      Platform Extensions function suffix             AMD

**Comment by claudeha** [comment]
Latest version works (I get an image and can zoom in and out).  Will need to read the documentation and/or source code to figure out how to use it better.  Thanks for the quick fix!

**Comment by jdanecki** [comment]
Thanks for confirmation. I've updated README.md with information about keys usage. Regarding dialog windows it's on my TODO list. I'll prepare wiki page with current TODO. Feel free to share any features you wanted to be added.

**Comment by jdanecki** [comment]
Closing this issue as the latest version works with multiple platforms.
